<a href="https://colab.research.google.com/github/Pogeyann/python/blob/main/EDA_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Basic Operations
--

In [ ]:
class Disease:
  def __init__(self,disease = 'Depression'):
    self.type =disease

  def getName(self):
    print(f'Mental Health Diseases: {self.type}')

d1 = Disease('Society Anxiety Disorder')
d1.getName()

Mental Health Diseases: Society Anxiety Disorder


In [ ]:
#Try catch block 
# the try block will generate a NameError , because x is not defined:

try:
  print(y)
except NameError:
  print('Well, the variable y is not defined')
except:
  print('OMG, Something else went wrong')

Well, the variable y is not defined


Numpy Array Basics
--

In [ ]:
import numpy as np

my1darray = np.array([1,8,27,64])
print(my1darray)

my2darray = np.array([[1, 2 , 3,4],[2, 4, 9, 16],[4, 8, 18, 32]])
print(my2darray)

ones = np.ones((3, 4))
print(ones)

zeros = np.zeros((2,3, 4),dtype=np.int16)
print(zeros)

np.random.random((2,2))

emptyArray = np.empty((3, 2))
print(emptyArray)

fullarray = np.full((2, 2),7)
print(fullarray)

evenSpacedArray = np.arange(10, 25, 5)
print(evenSpacedArray)

evenspaced = np.linspace(0,2,9)
print(evenspaced)

[ 1  8 27 64]
[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


Numpy array and file operations
--

In [ ]:
# Save anumpy array into file
x = np.arange(0.0,50,1)
np.savetxt('data.out', x, delimiter=',')

# Loading numpy array from text
z = np.loadtxt('data.out', unpack=True)
print(z)

#Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out',skip_header=1, filling_values=-999)

print(my_array2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


Inspecting numpy arrays
--

In [ ]:
# print the number of 'my2darray's dimensions
print(my2DArray.ndim)

#Print the number of 'my2DArray's elements
print(my2DArray.size)

#Print information about 'my2dArray's memory Layout
print(my2DArray.flags)

#Print the length of one array element in bytes
print(my2DArray.itemsize)

#Print the total consumed bytes by my2darray's elements
print(my2DArray.nbytes)

NameError: ignored

Broadcasting in NumPy

In [ ]:
a = np.ones((6,8))

print(a.shape)

y = np.random.random((10, 1, 8))

print(b.shape)

print(a + y)

(6, 8)
(6, 8)
[[[1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]
  [1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]
  [1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]
  [1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]
  [1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]
  [1.60111112 1.209086   1.47848105 1.26987664 1.05033879 1.1187631
   1.53456608 1.37900265]]

 [[1.86959489 1.18323779 1.43340219 1.87153535 1.06637651 1.08020155
   1.95444671 1.85650833]
  [1.86959489 1.18323779 1.43340219 1.87153535 1.06637651 1.08020155
   1.95444671 1.85650833]
  [1.86959489 1.18323779 1.43340219 1.87153535 1.06637651 1.08020155
   1.95444671 1.85650833]
  [1.86959489 1.18323779 1.43340219 1.87153535 1.06637651 1.08020155
   1.95444671 1.85650833]
  [1.86959489 1.18323779 1.43340219 1.87

Numpy array and file operations
--

In [ ]:
#save a numpy array into file
x = np.arange(0.0,50,1)
np.savetxt('data.out',x, delimiter=',')
z = np.loadtxt('data.out', unpack=True)
print(z)

my_array2 = np.genfromtxt('data.out',skip_header=1,filling_values=-999)

print(my_array2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


Inspecting numpy arrays
--

In [ ]:
print(my2DArray.flags)

NameError: ignored

Numpy array and file operations
--

Numpy and mathematics at work
--

In [ ]:
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9],[2, 3, -2]])

add = np.add(x, y)
print(add)

sub = np.subtract(x, y)
print(sub)

mul = np.multiply(x,y)
print(mul)

div = np.divide(x,y)
print(div)

rem = np.remainder(x, y)
print(rem)

Subset, Slice, and Index Arrays
--

In [ ]:
x = np.array([10,20, 30, 40, 50])

print(x[0:2])

y = np.array([[1, 2, 3, 4],[9, 10, 11, 12]])
print(y[0:2, 1])

#Specifying conditions
biggerThan2 = (y >= 2)
print(y[biggerThan2])


[10 20]
[ 2 10]
[ 2  3  4  9 10 11 12]


In [ ]:
#Importing pandas
import pandas as pd


Can you set default parameters in pandas?

In [ ]:
print('pandas version:',pd.__version__)

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows',500)

pandas version: 1.3.5


Data structure of pandas

* Series
* DataFrames.

In [ ]:
series = pd.Series([2, 3, 7, 11, 13, 17, 19, 23])
print(series)

dict_df = pd.DataFrame([{'A' : 'Apple', 'B':'Ball'},{'A':'Aeroplane','B':'Bat','C':'Cat'}])
dict_df = pd.DataFrame(dict_df)
print(dict_df)

#Creating dataframe from series
series_df = pd.DataFrame({
    'A': range(1,5),
    'B': pd.Timestamp('20190526'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3] * 4, dtype='int64'),
    'E': pd.Categorical(['Depression', 'Social Anxiety', 'Bipolar Disorder', 'Eating Disorder']),
    'F': 'Mental health',
    'G': 'is challenging'
})
print(series_df)

#Creating a dataframe from ndarrays
sdf = {
    'Country':['Ostfold','Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Baskerud'],
    'Iso-code': [1,2,3,4,5,6],
    'Area':[4180.69,4917.94,454.07,27397.76,25192.18]
}


0     2
1     3
2     7
3    11
4    13
5    17
6    19
7    23
dtype: int64
           A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat
   A          B    C  D                 E              F               G
0  1 2019-05-26  5.0  3        Depression  Mental health  is challenging
1  2 2019-05-26  5.0  3    Social Anxiety  Mental health  is challenging
2  3 2019-05-26  5.0  3  Bipolar Disorder  Mental health  is challenging
3  4 2019-05-26  5.0  3   Eating Disorder  Mental health  is challenging


Loading a dataset into Pandas DataFrame

In [ ]:
import pandas as pd
columns = ['age','workclass','fnlwgt','education','education_num','marital_status', 'occupation','relationship','ethnicity','gender','capital_gain']
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
df.head(10)


age               workclass  \
39  State-gov        77516   Bachelors   13           Never-married   
50  Self-emp-not-inc 83311   Bachelors   13      Married-civ-spouse   
38  Private          215646  HS-grad      9                Divorced   
53  Private          234721  11th         7      Married-civ-spouse   
28  Private          338409  Bachelors   13      Married-civ-spouse   
37  Private          284582  Masters     14      Married-civ-spouse   
49  Private          160187  9th          5   Married-spouse-absent   
52  Self-emp-not-inc 209642  HS-grad      9      Married-civ-spouse   
31  Private          45781   Masters     14           Never-married   
42  Private          159449  Bachelors   13      Married-civ-spouse   

                                                    fnlwgt       education  \
39  State-gov        77516   Bachelors        Adm-clerical   Not-in-family   
50  Self-emp-not-inc 83311   Bachelors     Exec-managerial         Husband   
38  Private          215646  HS-grad     Handlers-cleaners   Not-in-family   
53  Private          234721  11th        Handlers-cleaners         Husband   
28  Private          338409  Bachelors      Prof-specialty            Wife   
37  Private          284582  Masters       Exec-managerial            Wife   
49  Private          160187  9th             Other-service   Not-in-family   
52  Self-emp-not-inc 209642  HS-grad       Exec-managerial         Husband   
31  Private          45781   Masters        Prof-specialty   Not-in-family   
42  Private          159449  Bachelors     Exec-managerial         Husband   

                                       education_num marital_status  \
39  State-gov        77516   Bachelors         White           Male   
50  Self-emp-not-inc 83311   Bachelors         White           Male   
38  Private          215646  HS-grad           White           Male   
53  Private          234721  11th              Black           Male   
28  Private          338409  Bachelors         Black         Female   
37  Private          284582  Masters           White         Female   
49  Private          160187  9th               Black         Female   
52  Self-emp-not-inc 209642  HS-grad           White           Male   
31  Private          45781   Masters           White         Female   
42  Private          159449  Bachelors         White           Male   

                                        occupation  relationship  ethnicity  \
39  State-gov        77516   Bachelors        2174             0         40   
50  Self-emp-not-inc 83311   Bachelors           0             0         13   
38  Private          215646  HS-grad             0             0         40   
53  Private          234721  11th                0             0         40   
28  Private          338409  Bachelors           0             0         40   
37  Private          284582  Masters             0             0         40   
49  Private          160187  9th                 0             0         16   
52  Self-emp-not-inc 209642  HS-grad             0             0         45   
31  Private          45781   Masters         14084             0         50   
42  Private          159449  Bachelors        5178             0         40   

                                                gender capital_gain  
39  State-gov        77516   Bachelors   United-States        <=50K  
50  Self-emp-not-inc 83311   Bachelors   United-States        <=50K  
38  Private          215646  HS-grad     United-States        <=50K  
53  Private          234721  11th        United-States        <=50K  
28  Private          338409  Bachelors            Cuba        <=50K  
37  Private          284582  Masters     United-States        <=50K  
49  Private          160187  9th               Jamaica        <=50K  
52  Self-emp-not-inc 209642  HS-grad     United-States         >50K  
31  Private          45781   Masters     United-States         >50K  
42  Private          159449  Bachelors   United

In [ ]:
#Displays the rows, columns, data types, and memory used by the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32561 entries, (39, ' State-gov', 77516, ' Bachelors') to (52, ' Self-emp-inc', 287927, ' HS-grad')
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  object
 3   education       32561 non-null  object
 4   education_num   32561 non-null  object
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  int64 
 7   relationship    32561 non-null  int64 
 8   ethnicity       32561 non-null  int64 
 9   gender          32561 non-null  object
 10  capital_gain    32561 non-null  object
dtypes: int64(4), object(7)
memory usage: 3.6+ MB


Selecting rows and columns in the dataframe


In [ ]:
#selects a row
df.iloc[10:15]


age            workclass  \
37  Private   280464  Some-college   10   Married-civ-spouse   
30  State-gov 141297  Bachelors      13   Married-civ-spouse   
23  Private   122272  Bachelors      13        Never-married   
32  Private   205019  Assoc-acdm     12        Never-married   
40  Private   121772  Assoc-voc      11   Married-civ-spouse   

                                              fnlwgt       education  \
37  Private   280464  Some-college   Exec-managerial         Husband   
30  State-gov 141297  Bachelors       Prof-specialty         Husband   
23  Private   122272  Bachelors         Adm-clerical       Own-child   
32  Private   205019  Assoc-acdm               Sales   Not-in-family   
40  Private   121772  Assoc-voc         Craft-repair         Husband   

                                          education_num marital_status  \
37  Private   280464  Some-college                Black           Male   
30  State-gov 141297  Bachelors      Asian-Pac-Islander           Male   
23  Private   122272  Bachelors                   White         Female   
32  Private   205019  Assoc-acdm                  Black           Male   
40  Private   121772  Assoc-voc      Asian-Pac-Islander           Male   

                                    occupation  relationship  ethnicity  \
37  Private   280464  Some-college           0             0         80   
30  State-gov 141297  Bachelors              0             0         40   
23  Private   122272  Bachelors              0             0         30   
32  Private   205019  Assoc-acdm             0             0         50   
40  Private   121772  Assoc-voc              0             0         40   

                                            gender capital_gain  
37  Private   280464  Some-college   United-States         >50K  
30  State-gov 141297  Bachelors              India         >50K  
23  Private   122272  Bachelors      United-States        <=50K  
32  Private   205019  Assoc-acdm     United-States        <=50K  
40  Private   121772  Assoc-voc                  ?         >50K

In [ ]:
df.iloc[-2:]


age            workclass            fnlwgt  \
22  Private      201490  HS-grad    9        Never-married      Adm-clerical   
52  Self-emp-inc 287927  HS-grad    9   Married-civ-spouse   Exec-managerial   

                                   education education_num marital_status  \
22  Private      201490  HS-grad   Own-child         White           Male   
52  Self-emp-inc 287927  HS-grad        Wife         White         Female   

                                  occupation  relationship  ethnicity  \
22  Private      201490  HS-grad           0             0         20   
52  Self-emp-inc 287927  HS-grad       15024             0         40   

                                          gender capital_gain  
22  Private      201490  HS-grad   United-States        <=50K  
52  Self-emp-inc 287927  HS-grad   United-States         >50K

In [ ]:
df.iloc[::2,3:5].head()

education education_num
39  State-gov 77516   Bachelors   Not-in-family         White
38  Private   215646  HS-grad     Not-in-family         White
28  Private   338409  Bachelors            Wife         Black
49  Private   160187  9th         Not-in-family         Black
31  Private   45781   Masters     Not-in-family         White

In [2]:

import pandas as pd
import numpy as np

np.random.seed(24)

df = pd.DataFrame({'F': np.linspace(1,10,10)})

df = pd.concat([df,pd.DataFrame(np.random.randn(10,5), columns=list('EDCBA'))],axis=1)

df.iloc[0,2] = np.nan

df

F         E         D         C         B         A
0   1.0  1.329212       NaN -0.316280 -0.990810 -1.070816
1   2.0 -1.438713  0.564417  0.295722 -1.626404  0.219565
2   3.0  0.678805  1.889273  0.961538  0.104011 -0.481165
3   4.0  0.850229  1.453425  1.057737  0.165562  0.515018
4   5.0 -1.336936  0.562861  1.392855 -0.063328  0.121668
5   6.0  1.207603 -0.002040  1.627796  0.354493  1.037528
6   7.0 -0.385684  0.519818  1.686583 -1.325963  1.428984
7   8.0 -2.089354 -0.129820  0.631523 -0.586538  0.290720
8   9.0  1.264103  0.290035 -1.970288  0.803906  1.030550
9  10.0  0.118098 -0.021853  0.046841 -1.628753 -0.392361

In [3]:
# Define a function that should color the values that are less than 0
def colorNegativeValueToRed(value):
  if value < 0:
    color = 'red'
  elif value > 0:
    color = 'black'
  else:
    color = 'green'

  return 'color: %s ' % color

In [4]:
s = df.style.applymap(colorNegativeValueToRed, subset=['A','B','C', 'D', 'E'])
s

In [8]:
#Let us highlight max value in the column with green background and min value with orange
def highlightMax(s):
  if s = s.max():
    color = 'green'
  elif s = s.min():
    color = 'orange'
  else:
    color = 'red'

  return 'bakcolor: %' % color


In [11]:
df.style.apply(highlightMax, subset = ['A', 'B', 'C', 'D', 'E'])