<a href="https://colab.research.google.com/github/Pogeyann/python/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

sudo apt-get install python3-distutils

sudo pip install numpy

sudo apt install pip

#NUMPY
Numerical python-fixed type

Faster to read less bytes of memory

no type checking when iterating through objects

For Mathematical operations

Such as:matrix Operations,vectors,forrier transform,Linear Algebra

face recognition



#Why numpy is faster


*   Fixed Type
*   Contiguous memory - Contiguous memory allocation is basically a method in which a single contiguous section/part of memory is allocated to a process or file needing it. 



[100 110 90 120]

[200 210 180 170]

[110 120 90 150]

[210 250 240 270]

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


#SCIPY
Scientific python

using differentiation,integration,calculus



#Array
#Creating an array using numpy
 
 n-dimensional array-Creating an array using numpy

 Import numpy as np

 for pandas as pd


In [ ]:
#creating an array
import numpy as np
a=np.array([3,4,5,6,7])
print(type(a)) #ndimension array

<class 'numpy.ndarray'>


#Dimension

[1 2 3]

[4 5 6]

order(2*3)

rows=2,

columns=3

[1 3 4]
[5 6 7]
[4 3 1]
[6 7 8]

4*3 rows=4,columns=3::::::::

[1]
[2]
[3]
[4]

4*1

[1,2,3,4]

#Number of axis

1 D -only single axis(x)

2 D -x and Y axis, list within a list

3 D z,x,and y axis



#how to display dimension

#ndim    (x) -for printing dimension

In [ ]:
print(a.ndim)

1


Matrix order printing

MACHINE CALCULATES AS ROWS 

[3]

[4]

[5]

[6]

[7]


In [ ]:

print(a.shape)

(5,)


#2Dimension
 a=np.array([[ ]])

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[4,5,6,7,8]])

print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize) #bit size

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
10
8


In [ ]:
#2dimension 4*4 matrix
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,0]])
print(a)
print(a.shape)
print(a.ndim)
print(a[1][3])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]
 [7 8 9 0]]
(4, 4)
2
6


3 Dimension (2*2)  (z,x,y)

In [ ]:
import numpy as np
a=np.array([[[2,2],[2,4]]])
print(a)
print(a.ndim)
print(a.shape)

[[[2 2]
  [2 4]]]
3
(1, 2, 2)


#3 D (4*3)

In [ ]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4],[3,4,5],[4,5,6]]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 2 3]
  [2 3 4]
  [3 4 5]
  [4 5 6]]]
3
(1, 4, 3)
12


#2D 5*4

In [ ]:
a=np.array([[5,4,3,2],[4,3,2,1],[3,2,1,0],[2,1,0,0],[1,0,0,0]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[5 4 3 2]
 [4 3 2 1]
 [3 2 1 0]
 [2 1 0 0]
 [1 0 0 0]]
(5, 4)
2
20


#***Total no of elements in a matrix***

(3,4) ===> 12

(5,4) ===> 20

(6,5) ===> 30

(1,3,4) ==> 

**Size function is used**

In [ ]:
print(a.size)

12


2D total no.element 20)

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
print(a.ndim)
print(a)
print(a.size)
print(a.shape)

2
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
20
(4, 5)


#To print a datatype of a matrix

**Dtype function is used**

In [ ]:
print(a.dtype)

int64


slicing

#Different types of arrays

##Zero Matrix

eg:

[0,0,0]

[0,0,0]

[0,0,0]
(3*3)

[0 0 0]

[0 0 0]
(2*3)

zeros function


In [ ]:
import numpy as np
a=np.zeros([4,3])
b=np.zeros(5)
print(b)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)
2
float64


In [ ]:
import numpy as np
a=np.array([3,4],dtype=int)
print(a)

[3 4]


##zeros one dimension

In [ ]:
import numpy as np
a=np.zeros([15])
print(a)
print(a.ndim)
print(a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
15


##zeros 3dimension

In [ ]:
import numpy as np
a=np.zeros([1,5,4],dtype=int)
print(a)
print(a.ndim)
print(a.size)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
3
20


In [ ]:
a=np.zeros([2,5,4],dtype=int)
print(a)
print(a.ndim)
print(a.size)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
3
40


##Ones matrix
[1 1]
[1 1] (2*2)

[1 1 1] (2*3)

[1 0]

In [ ]:
import numpy as np
a=np.ones([4,5])
print(a)
print(a.dtype) #Default datatype is normally float

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [ ]:
import numpy as np
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###Be careful when copying arrays

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
b= a
b[0] = 100
print(a) #b=a and a.copy() are different

[1 2 3]
[100   2   3]


##One dimension 10

In [ ]:
import numpy as np
a=np.ones([20],dtype=int)
print(a)
print(a.size)
print(a.ndim)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
20
1


##3d one 4*4 dtype int

In [ ]:
import numpy as np
a=np.ones([1,4,4],dtype=int)
print(a)
print(a.size)
print(a.ndim)
print(a.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
16
3
int64


##Full matrix

matrix is created by passing a number,where matrix is created with that number

[5 5]     2*2 matrix

[4 4 4 4]

[4 4 4 4]

[4 4 4 4]  (3*4) matrix

In [ ]:
a=np.full([3,4],5)
print(a)
print(a.ndim)
print(a.size)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
2
12


In [ ]:
#(6*5) 3
a=np.full([6,5],3)
print(a)
print(a.size)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
30


one dimension 25

In [ ]:
a=np.full([25],2)
print(a)
print(a.ndim)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
1


3d (5*4) [4] [3 repeat]

In [ ]:
a=np.full([3,5,4],4)
print(a)
print(a.ndim)

[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]]
3


##Identity matrix

diagonal elements are 1 and others are zeros

[0 1]

[1 0] (2*2)


[1 0 0]

[0 1 0]

[0 0 1] (3*3)


[1 0 0 0]

[0 1 0 0]

[0 0 1 0] (3,4) not a identity matrix

should be square or symmetric matrix

In [ ]:
a=np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#total noof element 25
a=np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
a=np.identity(4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


##Complex numbers
a+ib

realpart :a
imaginery part:ib

eg:4+5j 4,5

In [ ]:
a=np.zeros([3,3],dtype=complex)
print(a)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [ ]:
a=np.ones([4,4],dtype=complex)
print(a)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


In [ ]:
a=np.full([4,4],4,dtype=complex)
print(a)

[[4.+0.j 4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j 4.+0.j]]


In [ ]:
a=np.array([[1+2j,4+5j,2+1j],[3+3j,6+3j,7+2j]])
print(a)
print(a.ndim)
print(a)

[[1.+2.j 4.+5.j 2.+1.j]
 [3.+3.j 6.+3.j 7.+2.j]]
2


##Random numbers
Random decimal numbers

In [ ]:
import numpy as np
np.random.rand(4,2 )

array([[0.79154473, 0.01709283],
       [0.7913197 , 0.20975145],
       [0.05148344, 0.81939158],
       [0.84075376, 0.76338417]])

In [ ]:
np.random.randint(-4,8, size=(3,3))

array([[-3,  3, -1],
       [ 1,  3,  1],
       [-4,  6,  0]])

##Repeat an array

In [ ]:
arr = np.array([1,2,3]) #1dimensional
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
arr= np.array([[1,2,3]]) #2 dimensional
r1 = np.repeat(arr,3, axis=1) #in column wise
print(r1)
r1= np.repeat(arr,3, axis=0) #in row wise 
print(r1)

[[1 1 1 2 2 2 3 3 3]]


#Reshaping  01/11/2022
3*4 matrix can be reshaped into 4*3 matrix

it is not possible to 5*2


In [ ]:
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
print(a)
print(a.shape)
b=a.reshape([3,4])
print(b)
print(b.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(4, 3)
[[1 2 3 1]
 [2 3 1 2]
 [3 1 2 3]]
(3, 4)


In [ ]:
a=np.array([[1,3,5,7,9],[2,4,6,8,10],[3,5,10,15,18],[4,6,7,8,9]])
print(a.shape)
print(a)
print('*'*100)
b=a.reshape([5,4])
print(b)
print('*'*100)
c=a.reshape([2,10])
print(c)
print('*'*100)
d=a.reshape([20])
print(d)
print(b.ndim)

(4, 5)
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]
 [ 3  5 10 15 18]
 [ 4  6  7  8  9]]
****************************************************************************************************
[[ 1  3  5  7]
 [ 9  2  4  6]
 [ 8 10  3  5]
 [10 15 18  4]
 [ 6  7  8  9]]
****************************************************************************************************
[[ 1  3  5  7  9  2  4  6  8 10]
 [ 3  5 10 15 18  4  6  7  8  9]]
****************************************************************************************************
[ 1  3  5  7  9  2  4  6  8 10  3  5 10 15 18  4  6  7  8  9]
2


#Flatten
for Reshaping into 1 dimensional matrix only converts into 1 dimensional

In [ ]:

a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a)
print('*'*100)
b=a.flatten()
print(b)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
****************************************************************************************************
[1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


#Arange (a-range)


In [ ]:
import numpy as np
a=np.arange(1,10)  #range(1,10)  (start,stop)
print(a)
a=np.arange(11,51)
print(a)


[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#1 to 20 element 5*4
a=np.arange(1,21)
print(a)
b=a.reshape([5,4])
print(b)
print('*'*100)
a=np.arange(1,21).reshape([5,4])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
****************************************************************************************************
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
a=np.arange(10)
print(a)
print('*'*100)
a=np.arange(10,40,2)
print(a)
print('*'*100)
a=np.arange(30,9,-1)   #30 to 10
print(a)

[0 1 2 3 4 5 6 7 8 9]
****************************************************************************************************
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
****************************************************************************************************
[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


[10,15,20,....50] [3*3]

In [ ]:
a=np.arange(10,51,5).reshape([3,3])
print(a)

[[10 15 20]
 [25 30 35]
 [40 45 50]]


#Linspace

In [ ]:
import numpy as np
a=np.linspace(5,50,10)
print(a)
a=np.linspace(10,100,5)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
[ 10.   32.5  55.   77.5 100. ]


In [ ]:
import numpy as np
a=np.arange(1,11)
print(a)
print(a[2])
print(a[7])
print(a[3:6])   #Index 3 4 5
print(a[2:6])
print(a[5:])    #5 to end of the list
print(a[:8])   #Index =0to 7
print(a[:3])
print(a[:])
print(a[3:9:3])  #index=3,6
print(a[2::3])  #index=2,5,8
print(a[::2]) #0,2,4,6,8
print(a[:8:2]) #0,2,4,6

[ 1  2  3  4  5  6  7  8  9 10]
3
8
[4 5 6]
[3 4 5 6]
[ 6  7  8  9 10]
[1 2 3 4 5 6 7 8]
[1 2 3]
[ 1  2  3  4  5  6  7  8  9 10]
[4 7]
[3 6 9]
[1 3 5 7 9]
[1 3 5 7]


02/11/2022 
#2D SLICING

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
print(a)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


in 2D [row,columns]  OOPS list problem(21

 0  1  2  3  4

[[1 2 3 4 5] 0

 [2 3 4 5 6] 1

 [3 4 5 6 7] 2

 [4 5 6 7 8]] 3 

In [ ]:
print(a[:2,:3])

[[1 2 3]
 [2 3 4]]


In [ ]:
print(a[:3,:4])


[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [ ]:
print(a[:4,1:4])

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
print(a[1:3,2:5])  #columns:2,3,4

[[4 5 6]
 [5 6 7]]


In [ ]:
print(a[2:,1:]) #row 2,3 #columns 1,2,3,4

[[4 5 6 7]
 [5 6 7 8]]


In [ ]:
print(a[1:4:2,1:5])  #row 1,3 column 1,2,3,4

[[3 4 5 6]
 [5 6 7 8]]


In [ ]:
b=np.array([[3,4,5,1,9],[3,9,6,5,3],[6,5,4,3,2],[5,9,8,7,6]])
print(b[:,:3]) #full rows 0,1,2
print(b[:,1:3]) #full rows 1,2
print(b[:2,:]) #0,1 row  and full columns
print(b[1:3,:]) #1,2 rows and full columns

[[3 4 5]
 [3 9 6]
 [6 5 4]
 [5 9 8]]
[[4 5]
 [9 6]
 [5 4]
 [9 8]]
[[3 4 5 1 9]
 [3 9 6 5 3]]
[[3 9 6 5 3]
 [6 5 4 3 2]]


zeroth row of data

zeroth column of data

In [ ]:
print(b[0,:])
print(b[:,0])

[3 4 5 1 9]
[3 3 6 5]


zeroth 0,2 and 1,3

full rows,2:4

complete row and columns

In [ ]:
print(b[0:3:2,1:4:2])
 print(b[:,2:5:2])
print(b[:,:])

[[4 1]
 [5 3]]
[[5 9]
 [6 3]
 [4 2]
 [8 6]]
[[3 4 5 1 9]
 [3 9 6 5 3]
 [6 5 4 3 2]
 [5 9 8 7 6]]


##Indexing

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print('*'*100)
print(a[1,5])
print(a[1,-2]) #get a specific element
print('*'*100)
print(a[0,:])
print('*'*100)
print(a[0,1:-1:2])
print('*'*100)
print(''*100) 
a[1,5]=20
print(a )
print('*'*100)

a[:,2] = [1,2]
print(a)
print('*'*100)
print('*'*100)
print('*'*100) 
#3d array
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print('*'*100)
print(b[0,1,1])
print('*'*100)
print(b[:,1,:])
print('*'*100)
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
****************************************************************************************************
13
13
****************************************************************************************************
[1 2 3 4 5 6 7]
****************************************************************************************************
[2 4 6]
****************************************************************************************************

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
****************************************************************************************************
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
****************************************************************************************************
****************************************************************************************************
****************************************************************************************************
[[[1 2]
  [3 4

#Mathematical operations

#Dot product

order should be same
operations perform between elements

In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
b=np.array([[3,4,5],[4,5,6],[5,6,7]])
print(a)
print(b)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [ ]:
c=np.add(a,b)
print(c)
c=np.subtract(a,b)
print(c)
c=np.multiply(a,b)
print(c)
c=np.divide(a,b)
print(c)

[[ 4  6  8]
 [ 6  8 10]
 [ 8 10 12]]
[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]
[[ 3  8 15]
 [ 8 15 24]
 [15 24 35]]
[[0.33333333 0.5        0.6       ]
 [0.5        0.6        0.66666667]
 [0.6        0.66666667 0.71428571]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
b=np.array([[3,4,5],[4,5,6],[5,6,7]])
c=np.multiply(a,b)
print(c)
#square
c=np.square(a) #square
print(c)
c=np.sqrt(a)  #square root
print(c)
np.cos(a)

[[ 3  8 15]
 [ 8 15 24]
 [15 24 35]]
[[ 1  4  9]
 [ 4  9 16]
 [ 9 16 25]]
[[1.         1.41421356 1.73205081]
 [1.41421356 1.73205081 2.        ]
 [1.73205081 2.         2.23606798]]


array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.41614684, -0.9899925 , -0.65364362],
       [-0.9899925 , -0.65364362,  0.28366219]])

#Dot product

In [ ]:
a=np.array([2,3,4])
b=np.array([4,5,6])
print(a)
print(b)
c=np.dot(a,b)
print(c)

[2 3 4]
[4 5 6]
47


In [ ]:
a=np.array([[3,4,5],[4,5,6],[3,1,3]])
b=np.array([[5,6,7],[4,2,1],[4,5,2]])
c=np.dot(a,b)
print(c)

[[51 51 35]
 [64 64 45]
 [31 35 28]]


#ROUND 03/11/22

#Floor division 
to discard the decimal part
(lowest integer)

In [ ]:
a=np.array([[1.2,2.5,3.1,4.5],[3.2,4.3,5.5,6.6],[4.4,5.1,6.2,7.3],[5.2,6.2,7.3,8.1]])
print(a)
b=np.floor(a)
print(b)


[[1.2 2.5 3.1 4.5]
 [3.2 4.3 5.5 6.6]
 [4.4 5.1 6.2 7.3]
 [5.2 6.2 7.3 8.1]]
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]


#Ceil function

converts a number to highest integer

In [ ]:
b=np.ceil(a)
print(b)


[[2. 3. 4. 5.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]
 [6. 7. 8. 9.]]


#Round
if odd no comes in 0.5 it converts to highest value 

eg 2.5==2

 5.5==6


In [ ]:
b=np.round(a)
print(b)

[[1. 2. 3. 4.]
 [3. 4. 6. 7.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]


#Sort

In [ ]:
a=np.array([1,5,6,2,3,4])
print(a)

[1 5 6 2 3 4]


TO calculate total sum of a matrix
sum function is used

In [ ]:
b=np.sum(a)
print(b)

21


In [ ]:
a=np.array([[3,6,5,3],[5,6,7,3],[3,7,6,5],[7,8,9,2]])
print(a)
b=np.sum(a)
print(b)
#axis=0  column count
b=np.sum(a,axis=0)
print(b)
#axis=1 row count
b=np.sum(a,axis=1)
print(b)

[[3 6 5 3]
 [5 6 7 3]
 [3 7 6 5]
 [7 8 9 2]]
85
[18 27 27 13]
[17 21 21 26]


In [ ]:
import numpy as np
a=np.array([[3,4,5],[4,5,6]])
b=np.array([[1,2],[2,3]])
c=np.dot(b,a)
print(c)

[[11 14 17]
 [18 23 28]]


#Sort function


In [ ]:
import numpy as np
a=np.array([6,3,8,9,2,1,0,4,7,10,5])
b=np.sort(a)
print(b)
#Sorts in ascending order


[ 0  1  2  3  4  5  6  7  8  9 10]


#Negative sorting


In [ ]:
b=np.sort(a)[::-1]
print(b)

[10  9  8  7  6  5  4  3  2  1  0]


#2D sorting


In [ ]:
import numpy as np
a=np.array([[2,3,4,5],[9,8,5,6],[2,10,7,8],[16,17,8,9]])
print(a)
b=np.sort(a)
print('*'*100)
print(b)

b=np.sort(a,axis=0) 
print('*'*100)
print(b)
print('*'*100)
b=np.sort(a,axis=1) #Default row wise
print(b)

[[ 2  3  4  5]
 [ 9  8  5  6]
 [ 2 10  7  8]
 [16 17  8  9]]
****************************************************************************************************
[[ 2  3  4  5]
 [ 5  6  8  9]
 [ 2  7  8 10]
 [ 8  9 16 17]]
****************************************************************************************************
[[ 2  3  4  5]
 [ 2  8  5  6]
 [ 9 10  7  8]
 [16 17  8  9]]
****************************************************************************************************
[[ 2  3  4  5]
 [ 5  6  8  9]
 [ 2  7  8 10]
 [ 8  9 16 17]]


In [ ]:
import numpy as np

b=np.sort(a,axis=None)

2D 3*4

descending order

row wise

column wise

In [ ]:
import numpy as np
a=np.array([[1,4,6,9],[6,5,2,9],[1,4,6,7]])
print(a)
print('*'*100)
b=np.sort(a,axis=0)[::-1]
print('2D slicing-')
c=-np.sort(-a,axis=1)
print('*'*100)
print(b)
print('*'*100)
print(c)

[[1 4 6 9]
 [6 5 2 9]
 [1 4 6 7]]
****************************************************************************************************
2D slicing-
****************************************************************************************************
[[6 5 6 9]
 [1 4 6 9]
 [1 4 2 7]]
****************************************************************************************************
[[9 6 4 1]
 [9 6 5 2]
 [7 6 4 1]]


#Arg sort
Sort list index values print


In [ ]:
import numpy as np
a=np.array([5,8,2,1,9,15,11,13,7,6,8,4])
b=np.argsort(a)
print(list(a))
print(b)

[5, 8, 2, 1, 9, 15, 11, 13, 7, 6, 8, 4]
[ 3  2 11  0  9  8  1 10  4  6  7  5]


In [ ]:
import numpy as np
a=np.array([[4,6,3,2],[3,7,4,6],[8,8,2,1],[6,5,3,4],[9,0,8,5]])
print(a)
print('*'*100)
b=np.argsort(a)
c=np.argsort(a,axis=0) #Column sorting
print('Row sorting')
print(b)
print('*'*100)
print('column sorting')
print(c)

[[4 6 3 2]
 [3 7 4 6]
 [8 8 2 1]
 [6 5 3 4]
 [9 0 8 5]]
****************************************************************************************************
Row sorting
[[3 2 0 1]
 [0 2 3 1]
 [3 2 0 1]
 [2 3 1 0]
 [1 3 2 0]]
****************************************************************************************************
column sorting
[[1 4 2 2]
 [0 3 0 0]
 [3 0 3 3]
 [2 1 1 4]
 [4 2 4 1]]


2D arg sorting(asc)

values  - values sort - index values

4 6 3 2 - 2 3 4 6 - 3 2 0 1

3 7 4 6 - 3 4 6 7 - 0 2 3 1

8 8 2 1 - 1 2 8 8 - 3 2 0 1

6 5 3 4 - 3 4 5 6 - 2 3 1 0

9 0 8 5 - 0 4 8 9 - 1 3 2 0

2D arg sorting(column sort)

values - values sort - index values

4 6 3 2 - 3 0 2 1 - 1 4 2 2

3 7 4 6 - 4 5 3 2 - 0 3 0 0

8 8 2 1 - 6 6 3 4 - 3 0 3 3

6 5 3 4 - 8 7 4 5 - 2 1 1 4

9 0 8 5 - 9 8 8 6 - 4 2 4 1

#Max value - statistics

In [ ]:
#07/11/2022
import numpy as np
a=np.array([5,3,2,6,7,10,15,17,25,22])
print(a)
b=np.max(a)
print('*'*100)
print(b)
b=np.argmax(a)
print('*'*100)
print(b)
print('*'*100)
a=np.array([[2,3,4,5],[9,8,5,6],[2,10,7,8],[16,17,8,9]])
print(a)
b=np.max(a,axis=0) #returns each columns max value
print('*'*100)
print(b)
b=np.argmax(a,axis=0) #Returns index values
print(b)
print('*'*100)
b=np.max(a,axis=1) #returns each rows max value
print(b)
b=np.min(a,axis=1)
print(b)
b=np.argmin(a,axis=1) #retuns min values indexes
print(b)

[ 5  3  2  6  7 10 15 17 25 22]
****************************************************************************************************
25
****************************************************************************************************
8
****************************************************************************************************
[[ 2  3  4  5]
 [ 9  8  5  6]
 [ 2 10  7  8]
 [16 17  8  9]]
****************************************************************************************************
[16 17  8  9]
[3 3 3 3]
****************************************************************************************************
[ 5  9 10 17]
[2 5 2 8]
[0 2 0 2]


#Iterations using arrays

In [ ]:
import numpy as np
a=np.array([5,3,2,6,7,10,15,17,25,22])
for i in a:
  print(i)

5
3
2
6
7
10
15
17
25
22


In [ ]:
a=np.array([[2,3,4,5],[9,8,5,6],[2,10,7,8],[16,17,8,9]])
for i in a:
  for j in i:
    print(j)

2
3
4
5
9
8
5
6
2
10
7
8
16
17
8
9


#Joining matrix
#Concatenate function

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])
c=np.concatenate((a,b))
print(c)


[1 2 3 4 5 6 4 5 6 7 8 9]


#2D joining

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[5,4,3]])
c=np.concatenate((a,b)) #default column vise
print(c)
print('*'*100)
c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 4 3]]
****************************************************************************************************
[[1 2 3 7 8 9]
 [4 5 6 5 4 3]]


#where 08/11

It returns the index values

In [ ]:
import numpy as np
a=np.array([5,6,7,8,4,3,2,4,6,5,4])
x=np.where(a%2==0)
print(x)

(array([ 1,  3,  4,  6,  7,  8, 10]),)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5]])
x=np.where(a%2==0)
print(x)

(array([0, 0, 1, 1]), array([1, 3, 0, 2]))


#filter

In [ ]:
import numpy as np
arr=np.array([41,42,43,44,45,46])
filter_arr=arr>42
print(filter_arr)
new_arr=arr[filter_arr]
print(new_arr)

[False False  True  True  True  True]
[43 44 45 46]


In [ ]:
#1 to 50 element array
#even number
import numpy as np
a=np.arange(1,51)
print(a)
x=np.where(a%2==0)
print(x)
filter_data=a%2==0
new_arr=a[filter_data]
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49]),)
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


#Vertically stacking vectors(extra)

In [ ]:
import numpy as np
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])#only considers when they has same columns


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])